create table if not exists Brand (id bigint generated by default as identity, name varchar(255) not null, syncVersion bigint, primary key (id));
create table if not exists CustomerOrder (id bigint generated by default as identity, name varchar(255) not null, syncVersion bigint, primary key (id));
create table if not exists CustomerOrder_Product (CustomerOrder_id bigint not null, products_id bigint not null, primary key (CustomerOrder_id, products_id));
create table if not exists Product (id bigint generated by default as identity, name varchar(255) not null, syncVersion bigint, brand_id bigint, primary key (id));
alter table CustomerOrder_Product add constraint if not exists UK_8m8cftcrq118d752cfft7n9wu unique (products_id);
alter table CustomerOrder_Product add constraint if not exists FK_8m8cftcrq118d752cfft7n9wu foreign key (products_id) references Product;
alter table CustomerOrder_Product add constraint if not exists FK_3neyx3svb46jblhh31oa7xjcg foreign key (CustomerOrder_id) references CustomerOrder;
alter table Product add constraint if not exists FK_e170op5kedic2jolyiimwqfaj foreign key (brand_id) references Brand;